// packages/word-tunnel/src/vue/WordTunnel.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, useId, watch } from 'vue'
import {
  DEFAULTS,
  buildConvergeKeyframes,
  buildWords,
  wordCountForWidth,
  type TunnelWord,
} from '../core/keywords'
import '../core/styles.css'

const props = withDefaults(
  defineProps<{
    words?: readonly string[]
    count?: number
    seed?: number
    perspective?: number
    innerRadius?: number
    outerRadius?: number
    travelMin?: number
    travelRange?: number
    fadeIn?: number
    fadeOut?: number
    color?: string
    fontSize?: number | string
    className?: string
    style?: Record<string, string | number>
  }>(),
  {
    seed: DEFAULTS.seed,
    perspective: DEFAULTS.perspective,
    innerRadius: DEFAULTS.innerRadius,
    outerRadius: DEFAULTS.outerRadius,
    travelMin: DEFAULTS.travelMin,
    travelRange: DEFAULTS.travelRange,
    fadeIn: DEFAULTS.fadeIn,
    fadeOut: DEFAULTS.fadeOut,
  },
)

const uid = useId().replace(/:/g, '')
const animName = `fx-wt-converge-${uid}`

const items = ref<TunnelWord[]>(
  buildWords({
    count: props.count ?? 80,
    seed: props.seed,
    words: props.words,
    innerRadius: props.innerRadius,
    outerRadius: props.outerRadius,
    travelMin: props.travelMin,
    travelRange: props.travelRange,
  }),
)

let resizeTimer: ReturnType<typeof setTimeout> | undefined

function rebuild() {
  const nextCount =
    props.count ??
    (typeof window !== 'undefined' ? wordCountForWidth(window.innerWidth) : 80)
  items.value = buildWords({
    count: nextCount,
    seed: props.seed,
    words: props.words,
    innerRadius: props.innerRadius,
    outerRadius: props.outerRadius,
    travelMin: props.travelMin,
    travelRange: props.travelRange,
  })
}

function onResize() {
  if (props.count != null) return
  if (resizeTimer) clearTimeout(resizeTimer)
  resizeTimer = setTimeout(rebuild, 150)
}

onMounted(() => {
  rebuild()
  window.addEventListener('resize', onResize)
})

onBeforeUnmount(() => {
  if (resizeTimer) clearTimeout(resizeTimer)
  window.removeEventListener('resize', onResize)
})

watch(
  () =>
    [
      props.count,
      props.seed,
      props.words,
      props.innerRadius,
      props.outerRadius,
      props.travelMin,
      props.travelRange,
    ] as const,
  () => rebuild(),
  { deep: true },
)

const keyframesCss = computed(() =>
  buildConvergeKeyframes(animName, props.fadeIn, props.fadeOut),
)

const rootClass = computed(() =>
  ['fx-wt', props.className].filter(Boolean).join(' '),
)

const rootStyle = computed(() => ({
  ...props.style,
  '--fx-wt-perspective': `${props.perspective}px`,
  '--fx-wt-anim': animName,
  ...(props.color ? { '--fx-wt-color': props.color } : null),
  ...(props.fontSize != null
    ? {
        '--fx-wt-font-size':
          typeof props.fontSize === 'number'
            ? `${props.fontSize}px`
            : props.fontSize,
      }
    : null),
}))
</script>

<template>
  <div :class="rootClass" :style="rootStyle">
    <component :is="'style'">{{ keyframesCss }}</component>
    <div class="fx-wt__stage" aria-hidden="true">
      <div class="fx-wt__space">
        <span
          v-for="(item, i) in items"
          :key="`${items.length}-${i}-${item.label}`"
          class="fx-wt__word"
          :style="{
            '--fx-wt-x': item.x,
            '--fx-wt-y': item.y,
            '--fx-wt-z0': `${item.z0}px`,
            '--fx-wt-z1': `${item.z1}px`,
            '--fx-wt-op': String(item.opacity),
            animationDuration: `${item.duration}s`,
            animationDelay: `${item.delay}s`,
          }"
        >
          {{ item.label }}
        </span>
      </div>
    </div>
    <div v-if="$slots.default" class="fx-wt__content">
      <slot />
    </div>
  </div>
</template>

// packages/word-tunnel/src/react/WordTunnel.tsx
'use client'

import {
  useEffect,
  useId,
  useMemo,
  useState,
  type CSSProperties,
  type ReactNode,
} from 'react'
import {
  DEFAULTS,
  buildConvergeKeyframes,
  buildWords,
  wordCountForWidth,
  type TunnelWord,
} from '../core/keywords'
import '../core/styles.css'

export type WordTunnelProps = {
  /** 词条列表；不传则用内置搞笑默认词。 */
  words?: readonly string[]
  /** 固定词数；不传则按视口宽度自适应。 */
  count?: number
  /** 布局随机种子：同值可复现，换值换分布。默认 `20250913`。 */
  seed?: number
  /** CSS perspective，默认 900。 */
  perspective?: number
  /** 中心空洞半径，越小词越靠近灭点。默认 8。 */
  innerRadius?: number
  /** 外圈采样半径。默认 52。 */
  outerRadius?: number
  /** z 轴最短飞行距离，越大消隐越靠近中心。默认 480。 */
  travelMin?: number
  /** z 轴额外随机飞行距离。默认 560。 */
  travelRange?: number
  /** 淡入完成进度 0–100。默认 10。 */
  fadeIn?: number
  /** 开始淡出进度 0–100，越大越晚消失。默认 88。 */
  fadeOut?: number
  /** 文字颜色。 */
  color?: string
  /** 字号，默认 24px。 */
  fontSize?: number | string
  className?: string
  style?: CSSProperties
  children?: ReactNode
  ariaHidden?: boolean
}

export function WordTunnel({
  words,
  count,
  seed = DEFAULTS.seed,
  perspective = DEFAULTS.perspective,
  innerRadius = DEFAULTS.innerRadius,
  outerRadius = DEFAULTS.outerRadius,
  travelMin = DEFAULTS.travelMin,
  travelRange = DEFAULTS.travelRange,
  fadeIn = DEFAULTS.fadeIn,
  fadeOut = DEFAULTS.fadeOut,
  color,
  fontSize,
  className,
  style,
  children,
  ariaHidden = true,
}: WordTunnelProps) {
  const uid = useId().replace(/:/g, '')
  const animName = `fx-wt-converge-${uid}`

  const layout = useMemo(
    () => ({
      seed,
      words,
      innerRadius,
      outerRadius,
      travelMin,
      travelRange,
    }),
    [seed, words, innerRadius, outerRadius, travelMin, travelRange],
  )

  const [items, setItems] = useState<TunnelWord[]>(() =>
    buildWords({
      count: count ?? 80,
      ...layout,
    }),
  )

  useEffect(() => {
    function rebuild() {
      const nextCount = count ?? wordCountForWidth(window.innerWidth)
      setItems(buildWords({ count: nextCount, ...layout }))
    }

    rebuild()

    if (count != null) return

    let timer: ReturnType<typeof setTimeout> | undefined
    function onResize() {
      if (timer) clearTimeout(timer)
      timer = setTimeout(rebuild, 150)
    }

    window.addEventListener('resize', onResize)
    return () => {
      if (timer) clearTimeout(timer)
      window.removeEventListener('resize', onResize)
    }
  }, [count, layout])

  const keyframesCss = useMemo(
    () => buildConvergeKeyframes(animName, fadeIn, fadeOut),
    [animName, fadeIn, fadeOut],
  )

  const rootStyle: CSSProperties = {
    ...style,
    ['--fx-wt-perspective' as string]: `${perspective}px`,
    ['--fx-wt-anim' as string]: animName,
    ...(color ? { ['--fx-wt-color' as string]: color } : null),
    ...(fontSize != null
      ? {
          ['--fx-wt-font-size' as string]:
            typeof fontSize === 'number' ? `${fontSize}px` : fontSize,
        }
      : null),
  }

  return (
    <div className={['fx-wt', className].filter(Boolean).join(' ')} style={rootStyle}>
      <style>{keyframesCss}</style>
      <div className="fx-wt__stage" aria-hidden={ariaHidden}>
        <div className="fx-wt__space">
          {items.map((item, i) => (
            <span
              key={`${items.length}-${i}-${item.label}`}
              className="fx-wt__word"
              style={{
                ['--fx-wt-x' as string]: item.x,
                ['--fx-wt-y' as string]: item.y,
                ['--fx-wt-z0' as string]: `${item.z0}px`,
                ['--fx-wt-z1' as string]: `${item.z1}px`,
                ['--fx-wt-op' as string]: String(item.opacity),
                animationDuration: `${item.duration}s`,
                animationDelay: `${item.delay}s`,
              }}
            >
              {item.label}
            </span>
          ))}
        </div>
      </div>
      {children != null ? <div className="fx-wt__content">{children}</div> : null}
    </div>
  )
}

export default WordTunnel
