// packages/button-kit/src/react/Button.tsx
'use client'

import {
  type ButtonHTMLAttributes,
  type CSSProperties,
  type ReactNode,
} from 'react'
import {
  BUTTON_VARIANTS,
  type ButtonVariant,
  variantClassName,
} from '../core/variants'
import '../core/styles.css'

export type ButtonProps = Omit<
  ButtonHTMLAttributes<HTMLButtonElement>,
  'className' | 'style' | 'children'
> & {
  /** Switch look by name: solid | outline | soft | glow | neon | shimmer | chroma | liquid | wipe | glass. */
  variant?: ButtonVariant | (string & {})
  children?: ReactNode
  className?: string
  style?: CSSProperties
}

export function Button({
  variant = 'solid',
  children,
  className,
  style,
  type = 'button',
  ...rest
}: ButtonProps) {
  const classes = [variantClassName(variant), className]
    .filter(Boolean)
    .join(' ')

  return (
    <button type={type} className={classes} style={style} {...rest}>
      {children}
    </button>
  )
}

export { BUTTON_VARIANTS, type ButtonVariant }
export default Button

// packages/button-kit/src/vue/Button.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue'
import { type ButtonVariant, variantClassName } from '../core/variants'
import '../core/styles.css'

const props = withDefaults(
  defineProps<{
    variant?: ButtonVariant | string
    className?: string
    style?: CSSProperties
    type?: 'button' | 'submit' | 'reset'
    disabled?: boolean
  }>(),
  {
    variant: 'solid',
    type: 'button',
  },
)

defineEmits<{
  click: [event: MouseEvent]
}>()

const rootClass = computed(() =>
  [variantClassName(props.variant), props.className].filter(Boolean).join(' '),
)
</script>

<template>
  <button
    :type="type"
    :class="rootClass"
    :style="style"
    :disabled="disabled"
    @click="$emit('click', $event)"
  >
    <slot />
  </button>
</template>
