// packages/starfield/src/react/Starfield.tsx
'use client'

import {
  useEffect,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from 'react'
import {
  createStarfield,
  type StarfieldInstance,
  type StarfieldOptions,
} from '../core/createStarfield'

export type StarfieldProps = StarfieldOptions & {
  children?: ReactNode
  className?: string
  style?: CSSProperties
  /** Accessible label for the canvas. */
  ariaLabel?: string
}

export function Starfield({
  children,
  className,
  style,
  ariaLabel = 'Starfield background',
  ...options
}: StarfieldProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const instanceRef = useRef<StarfieldInstance | null>(null)
  const [initialOptions] = useState(options)

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    instanceRef.current = createStarfield(canvas, initialOptions)
    return () => {
      instanceRef.current?.destroy()
      instanceRef.current = null
    }
  }, [initialOptions])

  useEffect(() => {
    instanceRef.current?.setOptions(options)
  })

  return (
    <div
      className={className}
      style={{ position: 'relative', overflow: 'hidden', ...style }}
    >
      <canvas
        ref={canvasRef}
        aria-label={ariaLabel}
        style={{
          position: 'absolute',
          inset: 0,
          width: '100%',
          height: '100%',
          display: 'block',
          pointerEvents: 'none',
        }}
      />
      {children != null ? (
        <div style={{ position: 'relative', zIndex: 1, height: '100%' }}>
          {children}
        </div>
      ) : null}
    </div>
  )
}

export default Starfield

// packages/starfield/src/vue/Starfield.vue
<script setup lang="ts">
import {
  computed,
  onBeforeUnmount,
  onMounted,
  ref,
  watch,
  type CSSProperties,
  type StyleValue,
} from 'vue'
import {
  createStarfield,
  type StarfieldInstance,
  type StarfieldOptions,
} from '../core/createStarfield'

const props = withDefaults(
  defineProps<{
    particleCount?: number
    color1?: string
    color2?: string
    color3?: string
    speed?: number
    density?: number
    starSize?: number
    focalDepth?: number
    turbulence?: number
    brightness?: number
    glitterIntensity?: number
    trailAmount?: number
    reverse?: boolean
    className?: string
    style?: CSSProperties
    ariaLabel?: string
  }>(),
  {
    ariaLabel: 'Starfield background',
  },
)

const canvasRef = ref<HTMLCanvasElement | null>(null)
let instance: StarfieldInstance | null = null

const rootClass = computed(() => props.className ?? '')
const rootStyle = computed(
  (): StyleValue => ({
    position: 'relative',
    overflow: 'hidden',
    ...props.style,
  }),
)

function optionPayload(): StarfieldOptions {
  return {
    particleCount: props.particleCount,
    color1: props.color1,
    color2: props.color2,
    color3: props.color3,
    speed: props.speed,
    density: props.density,
    starSize: props.starSize,
    focalDepth: props.focalDepth,
    turbulence: props.turbulence,
    brightness: props.brightness,
    glitterIntensity: props.glitterIntensity,
    trailAmount: props.trailAmount,
    reverse: props.reverse,
  }
}

onMounted(() => {
  const canvas = canvasRef.value
  if (!canvas) return
  instance = createStarfield(canvas, optionPayload())
})

onBeforeUnmount(() => {
  instance?.destroy()
  instance = null
})

watch(
  () => optionPayload(),
  (next) => {
    instance?.setOptions(next)
  },
  { deep: true },
)
</script>

<template>
  <div :class="rootClass" :style="rootStyle">
    <canvas
      ref="canvasRef"
      :aria-label="ariaLabel"
      style="
        position: absolute;
        inset: 0;
        width: 100%;
        height: 100%;
        display: block;
        pointer-events: none;
      "
    />
    <div v-if="$slots.default" style="position: relative; z-index: 1; height: 100%">
      <slot />
    </div>
  </div>
</template>
